source("./setup.R", chdir = TRUE)
source("./load_processed_data.R", chdir = TRUE)
source("./util_fns.R", chdir = TRUE)
source("./util_fns_fitting.R", chdir = TRUE)
source("./util_fns_epi_summary.R", chdir = TRUE)
source("./cov_make_pomp_model.R", chdir = TRUE)
source("./cov_make_pomp_model_gamma.R", chdir = TRUE)
source("./cov_make_pomp_model_vacc_effectiveness.R", chdir = TRUE)